version: '3.8'

services:

  db:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - fastapi-db-data:/var/lib/postgresql/data

volumes:
  fastapi-db-data: